Fixing the comparison for setting the input current limit to 900 mA.
arduino-libraries/Arduino_BQ24195 pull request #35
Opened 2023-08-02 15:42 UTC by rsingletonDS

This fixes the 900 mA input current limit setting. It doesn't have the double/float comparison fix you asked me to remove.

2023-08-02 15:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino-libraries/Arduino_BQ24195?pullRequest=35) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino-libraries/Arduino_BQ24195?pullRequest=35) before we can accept your contribution.<br/><hr/>**Rob Singleton** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino-libraries/Arduino_BQ24195?pullRequest=35) it.</sub>

2023-08-02 15:52 UTC, per1234 requested changes
Hi @rsingletonDS. Thanks so much for your pull request!

I see that the **@[]()CLAassistant** bot has not been able to validate the pull request.

As explained by the bot, this is likely caused by the email address used in your local Git settings not being associated with your GitHub account.

You can see the email address associated with the commit here:

https://api.github.com/repos/arduino-libraries/Arduino_BQ24195/commits/cc834bf70a0f07cede974455e3f3d06f12e33ed8

Please follow these instructions to resolve the issue:

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

Hopefully the check will automatically pass once that has been done. If not, please comment here and we will investigate.

2023-08-04 15:01 UTC, facchinm commented
As soon as the CLA is singed I'll go on and merge this (or probably @per1234 you can do it too :slightly_smiling_face: )

2025-05-20 00:34 UTC, per1234 reviewed
Closing as superseded by https://github.com/arduino-libraries/Arduino_BQ24195/pull/54

2025-05-20 00:34 UTC, closed without merging